
"use client"

import * as React from "react"
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card"
import { AlertTriangle, CheckCircle2, XCircle, TrendingUp, Search, Code, Activity, Trophy } from "lucide-react"
import { SEOAudit, CompetitorAnalysis } from "@/lib/types/job"
import { cn } from "@/lib/utils"

interface AuditReportProps {
    audit: SEOAudit
    competition: CompetitorAnalysis
    targetName: string
}

export function AuditReport({ audit, competition, targetName }: AuditReportProps) {

    // Color logic for grade
    const gradeColor =
        audit.overallGrade === 'A' ? 'text-green-500' :
            audit.overallGrade === 'B' ? 'text-blue-500' :
                audit.overallGrade === 'C' ? 'text-yellow-500' :
                    'text-red-500'

    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">

            {/* 1. Executive Summary & Opportunity Cost */}
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                <Card className="col-span-2 border-primary/20 bg-primary/5">
                    <CardHeader>
                        <CardTitle className="text-xl">Executive Audit Summary: {targetName}</CardTitle>
                        <CardDescription>Generated by Gemini Neural Engine</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <p className="text-muted-foreground leading-relaxed">
                            {audit.summary}
                        </p>
                        <div className="mt-6 flex flex-col gap-4">
                            <h4 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Monetization Analysis</h4>
                            <div className="flex flex-col md:flex-row gap-8">
                                <div className="flex flex-col">
                                    <span className="text-xs uppercase tracking-wider text-red-500/80 mb-1 font-bold">Estimated Leakage</span>
                                    <span className="text-3xl font-bold text-red-600 dark:text-red-400">
                                        {audit.monetization?.estimatedLostRevenue || "N/A"}
                                    </span>
                                    <span className="text-[10px] text-muted-foreground mt-1">Monthly revenue lost to competitors</span>
                                </div>
                                <div className="h-full w-px bg-border hidden md:block" />
                                <div className="flex flex-col">
                                    <span className="text-xs uppercase tracking-wider text-green-600/80 mb-1 font-bold">Projected Uplift</span>
                                    <span className="text-3xl font-bold text-green-600 dark:text-green-400">
                                        {audit.monetization?.potentialUplift || "N/A"}
                                    </span>
                                    <span className="text-[10px] text-muted-foreground mt-1">Addressable market capture</span>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <Card className="flex flex-col items-center justify-center p-6 bg-background/50 backdrop-blur-sm border-red-200 dark:border-red-900/30">
                    <div className="p-4 rounded-full bg-red-100 dark:bg-red-900/20 mb-4">
                        <Activity className="h-8 w-8 text-red-600 dark:text-red-400" />
                    </div>
                    <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-widest text-center">Digital Pulse</h3>
                    <div className="text-xl font-bold mt-2 text-center text-red-500">
                        Critical Visibility Void
                    </div>
                    <p className="text-xs text-center text-muted-foreground mt-4 px-4 leading-relaxed">
                        This business is currently invisible to modern search algorithms, resulting in a 0% capture rate for high-intent digital leads in the local area.
                    </p>
                </Card>
            </div>

            {/* 1.5. Revenue Opportunity (Monetization) */}
            {audit.monetization && (
                <Card className="bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-950/20 dark:to-emerald-900/10 border-green-200 dark:border-green-800">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 text-green-800 dark:text-green-400">
                            <TrendingUp className="h-5 w-5" />
                            Revenue Opportunity Analysis
                        </CardTitle>
                        <CardDescription>
                            Financial projection based on current digital performance gaps.
                        </CardDescription>
                    </CardHeader>
                    <CardContent className="grid gap-6 md:grid-cols-3">
                        <div className="space-y-1">
                            <span className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">Est. Monthly Revenue Loss</span>
                            <div className="text-3xl font-bold text-red-600 dark:text-red-400">
                                {audit.monetization.estimatedLostRevenue}
                            </div>
                            <p className="text-xs text-muted-foreground">Due to invisibility in local search.</p>
                        </div>
                        <div className="space-y-1">
                            <span className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">Potential Uplift</span>
                            <div className="text-3xl font-bold text-green-600 dark:text-green-400">
                                {audit.monetization.potentialUplift}
                            </div>
                            <p className="text-xs text-muted-foreground">With optimized infrastructure.</p>
                        </div>
                        <div className="p-4 rounded-lg bg-background/50 border border-green-200 dark:border-green-800">
                            <span className="text-xs uppercase tracking-wider text-muted-foreground font-semibold block mb-2">Recommended Strategy</span>
                            <div className="text-xl font-bold text-primary mb-1">
                                {audit.monetization.recommendedPackage} Package
                            </div>
                            <p className="text-xs text-muted-foreground leading-snug">
                                {audit.monetization.packageJustification}
                            </p>
                        </div>
                    </CardContent>
                </Card>
            )}

            {/* 2. Critical Failures Grid */}
            <div className="grid gap-6 md:grid-cols-2">
                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Code className="h-5 w-5 text-red-500" />
                            Technical Failures
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <ul className="space-y-3">
                            {audit.technicalIssues.map((issue, i) => (
                                <li key={i} className="flex items-start gap-2">
                                    <XCircle className="h-4 w-4 text-red-500 mt-1 shrink-0" />
                                    <span className="text-sm">{issue}</span>
                                </li>
                            ))}
                        </ul>
                    </CardContent>
                </Card>

                <Card>
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2">
                            <Search className="h-5 w-5 text-yellow-500" />
                            Content & SEO Gaps
                        </CardTitle>
                    </CardHeader>
                    <CardContent>
                        <ul className="space-y-3">
                            {audit.contentGaps.map((gap, i) => (
                                <li key={i} className="flex items-start gap-2">
                                    <AlertTriangle className="h-4 w-4 text-yellow-500 mt-1 shrink-0" />
                                    <span className="text-sm">{gap}</span>
                                </li>
                            ))}
                        </ul>
                        <div className="mt-6 pt-4 border-t">
                            <h4 className="text-xs font-semibold mb-2 uppercase text-muted-foreground">Missing High-Value Keywords</h4>
                            <div className="flex flex-wrap gap-2">
                                {audit.keywordsMissing.map((kw, i) => (
                                    <div key={i} className="px-2 py-1 bg-muted rounded text-xs font-mono">
                                        {kw}
                                    </div>
                                ))}
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>

            {/* 3. Competitive Landscape */}
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Trophy className="h-5 w-5 text-blue-500" />
                        Competitive Intelligence
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-sm text-muted-foreground mb-6 italic border-l-2 border-primary pl-4">
                        &quot;{competition.comparison}&quot;
                    </p>

                    <div className="grid gap-8 md:grid-cols-2">
                        <div>
                            <h4 className="text-sm font-semibold mb-3">Local Competitors (Weaknesses)</h4>
                            <div className="space-y-2">
                                {competition.localCompetitors.map((comp, i) => (
                                    <div key={i} className="flex justify-between items-center p-2 rounded bg-muted/50 text-sm">
                                        <span className="font-medium">{comp.name}</span>
                                        <span className="text-muted-foreground text-xs">Weakness: {comp.weakness}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div>
                            <h4 className="text-sm font-semibold mb-3">National Benchmarks (Strengths)</h4>
                            <div className="space-y-2">
                                {competition.nationalBenchmarks.map((comp, i) => (
                                    <div key={i} className="flex justify-between items-center p-2 rounded bg-muted/50 text-sm">
                                        <span className="font-medium">{comp.brand}</span>
                                        <span className="text-green-600 dark:text-green-400 text-xs font-semibold">{comp.strength}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </CardContent>
            </Card>

        </div >
    )
}
