export const INDUSTRIES = [
    'Accounting & CPA',
    'Auto Detailing',
    'Auto Repair',
    'Bakeries',
    'Barbershops',
    'Body Shops',
    'Car Dealerships',
    'Catering',
    'Chiropractors',
    'Cleaning Services',
    'Coffee Shops',
    'Dentists',
    'Electrical',
    'Event Planning',
    'Financial Advisors',
    'Flooring',
    'Florists',
    'Garage Doors',
    'General Contractor',
    'Gyms & Fitness',
    'Handyman',
    'Home Inspection',
    'Hotels',
    'HVAC',
    'Insurance',
    'IT Services',
    'Landscaping',
    'Lawyers',
    'Locksmith',
    'Massage Therapy',
    'Mortgage Brokers',
    'Moving Services',
    'Painting',
    'Pest Control',
    'Pet Grooming',
    'Photography',
    'Physical Therapy',
    'Plumbing',
    'Property Management',
    'Real Estate',
    'Restaurants',
    'Roofing',
    'Salons',
    'Security Systems',
    'Solar',
    'Spas',
    'Towing',
    'Veterinarians',
    'Web Design',
    'Windows & Doors',
    'Yoga Studios'
];
