
import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/firebase-admin'
import { runIdentityGenerationPhase } from '@/lib/server/services/antigravity-core'
import { PlaceResult } from '@/lib/server/services/google-places'

// Manual Trigger for "EXECUTE BRANDLIFT_VARIANT_ENGINE"
export async function POST(req: NextRequest) {
    try {
        const body = await req.json()
        const { industry_vector, entity_name, user_input } = body

        if (!industry_vector || !entity_name) {
            return NextResponse.json({ error: "Missing required fields: industry_vector, entity_name" }, { status: 400 })
        }

        const slug = entity_name.toLowerCase().replace(/[^a-z0-9]/g, '-')
        const jobId = `manual_${slug}_${Date.now()}`

        // Mock PlaceResult based on inputs (Cast as PlaceResult to satisfy interface)
        const target = {
            name: `places/${slug}`, // Resource name format
            formattedAddress: "Phoenix, AZ (Manual Entry)",
            displayName: { text: entity_name, languageCode: 'en' },
            primaryType: industry_vector,
            rating: 5.0,
            userRatingCount: 1,
            websiteUri: `https://${slug}.com`,
            businessStatus: "OPERATIONAL",
            location: { latitude: 33.4484, longitude: -112.0740 }, // Extra, but kept for context if needed
            topReview: "Automatically generated by BrandLift Variant Engine."
        } as unknown as PlaceResult

        if (!db) {
            return NextResponse.json({ error: "Database not initialized" }, { status: 500 })
        }

        // Create Job Record
        await db.collection("antigravity_jobs").doc(jobId).set({
            id: jobId,
            status: 'generating_identity',
            industry: industry_vector,
            location: "Phoenix, AZ",
            strategy: 'manual_variant_engine',
            userInput: user_input,
            createdAt: new Date(),
            updatedAt: new Date(),
            logs: [`[Variant Engine] Initialized for ${entity_name}`],
            result: {
                domain: `${slug}.brandlift.ai`,
                topCandidate: target,
                vacuumCandidates: 1
            }
        })

        // Run Identity Generation (Background)
        // Note: we don't await this so the API returns quickly, but in serverless/Vercel this might be cut off.
        // For local dev, this is fine. For production, use a queue.
        runIdentityGenerationPhase(jobId, industry_vector, "Phoenix, AZ", target, {
            // Mock SEO Audit
            technicalScore: 85,
            contentScore: 70,
            overallGrade: 'B',
            summary: "Manual run initiated via Variant Engine.",
            technicalIssues: [],
            contentGaps: [],
            keywordsMissing: [],
            marketOpportunity: "High",
            painPoints: ["Visibility", "Conversion"]
        }, 'generic').catch(err => console.error("Manual Variant Gen Failed", err))

        return NextResponse.json({
            success: true,
            jobId,
            dashboardUrl: `http://localhost:3000/demo/${slug}`
        })

    } catch (e) {
        console.error("Variant Engine API Error", e)
        return NextResponse.json({ error: String(e) }, { status: 500 })
    }
}
